name: TryPipeline
on:
  [push, workflow_dispatch]
  
jobs:
  apiRobotTest:
    name: Robot - Api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-requests
      - name: Start Test
        run: |
          python -m robot -i api test/RobotFramework/tc.robot
