name: TryPipeline
on:
  [push, workflow_dispatch]
  
jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "PipelineTest"

  secondJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "PipelineTest2"
